### ISSUE TITLE
Not perfect work for horizontal orientation

### ISSUE THREAD

**Issue by NguyenDuck** [Nain57/Smart-AutoClicker#4] opened 2021-05-21 02:34 UTC
It's working perfect in vertical mode, but some functional don't work in horizontal screen mode. Fix that!

**Comment by Nain57** [comment] 2021-05-21 08:05
I haven't thought of testing it in horizontal. 
Can you provide me more details about what is not working ?

I'm on vacation and will get back at home next Wednesday, I will fix it then

**Comment by NguyenDuck** [comment] 2021-05-22 01:52
![20210522_084821](https://user-images.githubusercontent.com/83252725/119211167-b65b3680-bada-11eb-8121-caed27e6e5f1.jpg)
![20210522_084836](https://user-images.githubusercontent.com/83252725/119211179-bce9ae00-bada-11eb-8e00-c1cfa1b1a2ee.jpg)
![20210522_084856](https://user-images.githubusercontent.com/83252725/119211183-c410bc00-bada-11eb-887a-6b6efe988ac3.jpg)
![20210522_084906](https://user-images.githubusercontent.com/83252725/119211187-d4289b80-bada-11eb-9d5b-bd26f59f9cda.jpg)

Autoclicker not auto change self orientation on other app.

**Comment by NguyenDuck** [comment] 2021-05-22 01:55
I'll wait that's fixed in next release!
Thank you for support! 😀

**Comment by Nain57** [comment] 2021-05-22 08:42
Thanks for the screenshots !

**Comment by Nain57** [comment] 2021-05-26 13:01
I'm currently working on the issue.
The menu position should be fixed by https://github.com/Nain57/Smart-AutoClicker/commit/4a5eb906d55e7cd3464f157eac9735a86a814ed6. Portrait and landscape orientation now have their own positions.

But it have highlighted other bugs in the screen capture: If you rotate the screen after a scenario have been started, all captures and detections will not work as intended. This is a bit more complicated to fix, I'm working on it but it might take some time

**Comment by realmain** [comment] 2021-06-04 15:49
Also can't wait to see this fixed. This would be great for games too since most mobile games are horizontal.

**Comment by Nain57** [comment] 2021-06-04 15:52
Current master is working, I just have to fix some edge cases.
I quite busy but I will try to finish this weekend

**Comment by Nain57** [comment] 2021-06-07 13:35
This should be fixed with version 1.0-RC2 : https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.0-RC2
It should be soon released on F-Droid, but the .apk is already available with the release note.

I will close this ticket upon your confirmation.

**Comment by realmain** [comment] 2021-06-08 05:51
Issue: You can't scroll down in horizontal view to adjust **Tolerated difference**. I have to go back to home screen for vertical view to adjust it each time.

![](https://i.imgur.com/P5EyptS.jpg)

![](https://i.imgur.com/bfBCuVq.jpg)

![](https://i.imgur.com/LRUciaO.jpg)

**Comment by Nain57** [comment] 2021-06-08 09:17
Thanks for your tests.
I have added a ScrollView to this dialog as well to stay consistent with the other dialogs. You can now scroll it.

This is fixed in 1.0-RC3 available here: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.0-RC3

**Comment by realmain** [comment] 2021-06-09 05:05
With 1.0-RC3, everything seems to be working fine so far. Haven't encountered any issues on my end.

**Closed** 2021-06-10 09:19 UTC
Labels: bug
