### ISSUE TITLE
Auto Clicker not working on some apps

### ISSUE THREAD

**Issue by BaconCondensate** [Nain57/Smart-AutoClicker#389] opened 2024-02-25 03:42 UTC
**Describe the bug**
Some apps seems to block accessibility based auto clicker.  Tested with 'Brawl Stars'

**To Reproduce**
1. Open offending apps
2. Use autoclicker

**Expected behavior**
It should click, root based clicker seems to work

**Smartphone (please complete the following information):**
 - Device: Poco X3 Pro
 - Android OS version: Android 13, LineageOS 20
 - Smart AutoClicker version: 2.4.2

**Comment by Nain57** [comment] 2024-03-04 12:23
Tested OK on with Brawl Stars (menus and in game):
* Android 14 OnePlus 10 Pro
* Android 13 OnePlus 7 Pro
* Android 10 Emulator
* Android 9 Pixel C

This issue can be caused by:
* the debug overlay is enabled => Some brands doesn't follow standard AOSP behaviour on floating windows opacity and touch capture rules, leading to the incapacity of clicking when it is enabled.
* the condition is not detected => Ensure your conditions are correctly detected. Scenario detection quality and condition threashold can help you fine tune the detection depending on the screen display conditions. 


To verify if the app can actually click on the screen, you can create a Simple scenario, and just test a simple click action. The code is exactly the same for both use case

**Comment by BaconCondensate** [comment] 2024-03-19 08:28
That's weird, I tried both simple and smart scenario, both does not work

enabling debug in the smart clicker shows that it did something, just that it's not registered by the game

I have also tested with Samsung Tab S6 Lite, also running the latest official lineageOS, the issue seems to also be there

**Comment by sourcelocation** [comment] 2024-04-19 12:57
Bump, same issue

**Comment by sourcelocation** [comment] 2024-04-26 18:20
Issue seems to be fixed now...? After the latest update clicks now go through

**Closed** 2024-09-01 09:23 UTC
Labels: bug

**Comment by zioth** [comment] 2024-10-21 22:15
I'm seeing this on the latest update to the game, "The Tower." It seems to be blocking accessibility clicks from all auto-clickers I've tried including yours.

**Comment by macdaddymario** [comment] 2024-10-25 11:24
Am seeing this issue in the game Dokkan Battle.

Other clicker apps seem to work, but this one, when opening the game (ZFold 5), the floating menu vanishes and nothing works. Floating menu shows up again when switching to another app.

**Comment by gozfrt** [comment] 2025-01-07 15:19
> Am seeing this issue in the game Dokkan Battle.
> 
> Other clicker apps seem to work, but this one, when opening the game (ZFold 5), the floating menu vanishes and nothing works. Floating menu shows up again when switching to another app.

Yeah same with me, Dokkan and Fortnite both suddenly became unusable with Klickr

**Comment by zioth** [comment] 2025-01-07 16:26
Still doesn't work in "The Tower." The game seems to be blocking accessibility taps.

**Comment by gozfrt** [comment] 2025-01-07 16:42
> Still doesn't work in "The Tower." The game seems to be blocking accessibility taps.

just spam the play button, it will start the scenario after a while. That works for me with Dokkan Battle.
