### ISSUE TITLE
Accessibility service

### ISSUE THREAD

**Issue by Xerizaf** [Nain57/Smart-AutoClicker#159] opened 2022-08-06 03:11 UTC
First time I run the app everything works fine: I give permissions, also to accessibility service, and it works. But from then on everytime I try to make the app work it asks me to enable accessibility service again, when the option is already enabled, but It says that this service doesn't works properly. I'm using a Xiaomi Redmi Note 10 Pro. What I have to do to prevent this ti happen? Thank you.

**Comment by 19ChuAnh13** [comment] 2022-08-07 15:34
That's because of MIUI Rom

**Comment by ghost345-bit** [comment] 2022-08-30 12:41
So there is no way of fixing it?

**Comment by Nain57** [comment] 2022-08-30 12:45
Depending on the phone brand and Android version, there is several tips you can apply to keep Smart Autoclicker alive.
Follow the instructions here: https://dontkillmyapp.com

**Comment by Nain57** [comment] 2022-09-08 11:08
Duplicate of: https://github.com/Nain57/Smart-AutoClicker/issues/161

**Closed by Nain57** 2022-09-08 11:08 UTC
Labels: duplicate
