### ISSUE TITLE
Daisy chain scenarios

### ISSUE THREAD

**Issue by Metazolid** [Nain57/Smart-AutoClicker#199] opened 2022-11-24 23:08 UTC
I've got a couple scenarios for one game, and would like to kinda pack them all in one scenario, to avoid switching back and forth depending on the situation.
It would be very useful to have a 5th action called "Chain Scenario" that would just start the scenario you pick.

Not sure if it's a good option to loop the new scenario indefinitely like it's already the case or then hand it back to the previous Scenario once it's run its course but daisy chaining scenarios would be great to have.

**Comment by Nain57** [comment] 2023-01-22 18:05
Duplicate of https://github.com/Nain57/Smart-AutoClicker/issues/56

**Closed by Nain57** 2023-01-22 18:05 UTC
Labels: duplicate
