### ISSUE TITLE
Waydroid no clicking

### ISSUE THREAD

**Issue by Quackdoc** [Nain57/Smart-AutoClicker#204] opened 2022-12-16 10:32 UTC
it succsessfuly finds the area to click on, logcat gets spammed with the error below when it tries to click
`SmartAutoClickerService: Gesture cancelled: android.accessibilityservice.GestureDescription@`

possibly related to #196

**Comment by Nain57** [comment] 2023-01-22 18:08
Duplicate of https://github.com/Nain57/Smart-AutoClicker/issues/196

**Closed by Nain57** 2023-01-22 18:08 UTC
Labels: duplicate
