### ISSUE TITLE
When editing a scenario, new actions always get added to index 2

### ISSUE THREAD

**Issue by scratchermatch** [Nain57/Smart-AutoClicker#518] opened 2024-10-05 00:18 UTC
### Version of Smart AutoClicker

3.04

### Device brand and model

pixel 3

### Version of your Android OS

14

### Type

Smart scenario

### Describe what happened?

I have a very complex scenario with some events having sequences of hundreds of unique actions. When I go to any of them and add a new actions at the final index, in the UI it shows as having the correct index, but when I go to save, all new actions added that session go to index 2 and forwards, completely disrupting the flow and ruining the scenario. Because the only way to reorder is to click each new item and move it manually with the 2 buttons or type in the new index, this is extremely tedious to fix. I can't select and move multiple actions at once either.

### Describe what should have happened?

If I have a list of 20 actions and I scroll to item 20 and add new actions, they should remain at indices 21+ as shown in the UI instead of placing themselves at index 2+ when I save.

**Comment by Nain57** [comment] 2024-10-12 14:18
Hi and thank you for your feedback.

A similar issue has been in 3.0.1 and I can't reproduce the issue since them. Please provide the backup zip file of the scenario causing the issue and a video in order to help me understand what is happening.

Also as a note, you should not use hundreds of actions in a single event. Even if Klick'r is allowing it, it has not been made to work like that. You should always set up your smart scenario to behave like a human, a few actions triggered by something displayed on the screen.

**Comment by scratchermatch** [comment] 2024-10-14 20:48
I've attached the backup and the video.

The first thing I moved is a wait that I placed at the end of the scenario the last time I opened it. You can see the scenario run, and then I add two more items, a recorded click and an 800ms wait. They go to index 2 instead of at the end where I added them. Hopefully this helps.

As a side note, the UI is extremely tedious to move things around in. I can move an item by typing a new index, but the only way for me to go back to the start to move another item was to drag 38 times to the left. The legacy UI list view is okay, but it is very hard to move items in it, especially since I forget which click is which as it doesn't show the location of the click. It would be incredibly useful to be able to give names to actions like "click backpack" instead of just "click" and then be able to reuse that item in the future.
[SmartAutoClicker-Backup (1).zip](https://github.com/user-attachments/files/17369259/SmartAutoClicker-Backup.1.zip)

https://github.com/user-attachments/assets/80b3e1ce-1753-4980-9681-a77d2225babb

**Comment by scratchermatch** [comment] 2024-10-14 20:54
Well looking back and watching the video now, it looks like it didn't record properly, probably as a result of klickr also using the record function at the same time. Normally the app records okay.

Since I can't record it, I'll try to describe it as accurately as I can:
I open the scenario. I run the scenario. It completes. I open the "floor 2" screen event. I move the incorrectly placed item #2 to the very end of the list. I then add 2 new item to the end. A click, and then a 800ms wait. I press the save button, and then reopen "floor 2". Both of those actions moved to index 2. Specifically, the click moved to index 2 and the wait moved to index 3. I move them back to the end where they belong. I hit save. This time they stay in the correct place. Now the scenario runs fine with the added actions.

If I find a way to record the app, I will upload a video and let you know.

**Comment by Nain57** [comment] 2024-10-20 11:44
Thank you for your clarifications. 
I have finally been able to reproduce it, currently working on a solution.

**Comment by Nain57** [comment] 2024-10-20 12:55
Should be fixed by https://github.com/Nain57/Smart-AutoClicker/commit/11d0ef8a9eec68211bc3ea2c47dce68d467c4903

**Comment by Nain57** [comment] 2024-10-20 13:50
Fix available in 3.0.6: https://github.com/Nain57/Smart-AutoClicker/releases/tag/3.0.6
If you still encounter this issue, feel free to reopen tis ticket.

**Closed by Nain57** 2024-10-20 13:50 UTC
Labels: bug, acknowledged
