### ISSUE TITLE
[Feature Request] Minimum image capture area. Manual input of image search coordinates. Etc....

### ISSUE THREAD

**Issue by Gorq771** [Nain57/Smart-AutoClicker#217] opened 2023-01-24 14:07 UTC
1. Rotating the screen changes the minimum image capture area to a rectangle. In the normal position, the area has the shape of a square.
As a result, in a horizontal position, a very wide rectangle, even when approaching.
Add the ability to change the rectangle to a square when the screen is rotated.
P.s. yes, I am aware of the possibility of zooming in for a more accurate capture.

2. In addition to 1. - add the ability to change the minimum image capture area.
The search area is large, even when the screen is zoomed in and the search area is reduced.

3. In the clicker settings there are only two image search areas - on the entire screen or in an area equal to the size of the image.
Add the ability to manually enter coordinates for the search area.

4. Add the ability to edit an already created image.
Do not delete and make a new capture, namely editing an already created one, for example, cropping.

5. The problem of recognizing a picture with transparent elements.
"Clickermann" for PC has the ability to take pictures and search in black and white "colormode(8)", which helps to combat transparent backgrounds.
Please add this feature.

6. Add the ability to switch between different scenarios without closing (minimizing) the program.

7. The application conflicts with the "Tap Translate Screen" translator.
If you translate the text with this translator, and then press the triangle to start scenario, nothing will happen, but other buttons work - stop and move.

**Comment by Nain57** [comment] 2023-01-29 20:44
Hi and thanks for this issue.
In the future, try to create several issue for each ideas, as it is easier to track.

1 & 2: next version have changed and improved the capture area management. This version should be released soon, as it is currently in heavy testing.
3: Duplicate of https://github.com/Nain57/Smart-AutoClicker/issues/190
4 & 5: Actual new features requests.
6: Duplicate of https://github.com/Nain57/Smart-AutoClicker/issues/144
7: This might be a conflict issue that might come from my app of this other app. Please create a bug ticket and provide this application details and installation link.

**Closed** 2023-08-12 10:57 UTC
Labels: enhancement
