### ISSUE TITLE
Screen detected but no action at all

### ISSUE THREAD

**Issue by EnKiu** [Nain57/Smart-AutoClicker#196] opened 2022-11-14 00:30 UTC
Your application is really great, easy to use, config and very fast detection.
But i do not know why 1 step of my config does not work as it shout be.
I open debug message to show, it already detect the step but no click/swipe performed.

Please let me know if i wrong or contact me.
I can code, if you want, i can learn and join distribution team.

Thanks!
![Screenshot_20221114-072312_Champions](https://user-images.githubusercontent.com/49906777/201552908-6571c514-8622-469f-b5dc-2565e45cc421.jpg)
![Screenshot_20221114-072326_Champions](https://user-images.githubusercontent.com/49906777/201552917-f04722e6-4ebc-467c-8ea3-8342de49c762.jpg)
![Screenshot_20221114-072330_Champions](https://user-images.githubusercontent.com/49906777/201552921-4133457c-7c76-4ade-9fcd-557d831c6bc7.jpg)
![Screenshot_20221114-072332_Champions](https://user-images.githubusercontent.com/49906777/201552923-8b2f2555-9357-4b50-9985-4e1fbb229b2b.jpg)
![Screenshot_20221114-072334_Champions](https://user-images.githubusercontent.com/49906777/201552926-4332c953-47a4-434f-9e0b-bf6948ae7731.jpg)

**Comment by XiangXena** [comment] 2022-12-03 00:41
I'm having this issue too, the only temporary fix I know is to full restart the device, and closing and reopening the app doesn't help.

**Comment by EnKiu** [comment] 2023-01-05 06:55
I debug myself and found something might be the problem.
Everything is fine, the code still do the gesture and prompt out NQMinh Gesture complete as my logcat

![Ảnh chụp Màn hình 2023-01-05 lúc 13 52 36](https://user-images.githubusercontent.com/49906777/210719528-9425b6ee-51f3-4c37-a183-4e1a9c24f905.png)

But back from the executeClick, it define context is Main. Might be this game have special context when come to this screen so the action do not send to the right context
![Ảnh chụp Màn hình 2023-01-05 lúc 13 51 33](https://user-images.githubusercontent.com/49906777/210719505-a9aaec5b-ca25-4b07-b2b0-783c20324d55.png)
![Ảnh chụp Màn hình 2023-01-05 lúc 13 52 07](https://user-images.githubusercontent.com/49906777/210719520-f02ee6e3-97e8-4b32-a4bc-cfd3013bf72b.png)

**Comment by Nain57** [comment] 2023-01-22 17:46
I have investigated this issue, and it seems caused by a restriction from Android with version 11+. As the menu overlay is too big, Android is preventing the click injections to avoid app the tries to scam the user.

You can reduce the occurrences of this issue by disabling the debug mode (as the overlay will be smaller).
Next version will change the menu display (and debug mode) in order to avoid this bug.

**Closed** 2023-02-22 12:44 UTC
Labels: bug
