### ISSUE TITLE
After the first execution, the floating menu is left with only 2 options

### ISSUE THREAD

**Issue by debukomori** [Nain57/Smart-AutoClicker#500] opened 2024-09-16 21:06 UTC
### Version of Smart AutoClicker

3.0.3

### Device brand and model

poco x3 gt / BlueStacks

### Version of your Android OS

13 , 9

### Type

Other

### Describe what happened?

In version 2.3.5, the floating menu displays 4 buttons. Starting from version 2.4.0, only 2 buttons are displayed.
![2 3 5](https://github.com/user-attachments/assets/748e692f-78d9-47be-ad71-a579cf5cc071)
![3 0 3](https://github.com/user-attachments/assets/66cf3b0e-3080-4b27-8775-7dcd949e40bc)

### Describe what should have happened?

displays 4 buttons

**Comment by Nain57** [comment] 2024-09-16 21:39
Issue caused by disabled animations in developper options. Duplicate of https://github.com/Nain57/Smart-AutoClicker/issues/480

**Closed by Nain57** 2024-09-16 21:39 UTC
Labels: bug
