### ISSUE TITLE
Continuous clicking

### ISSUE THREAD

**Issue by varandas79** [Nain57/Smart-AutoClicker#226] opened 2023-02-19 19:57 UTC
Is that possible to include a continuous clicking option?
With infinite or a finite defined numbers of clicks, and frequency or time between clicks.
Thanks for that great App

**Comment by Nain57** [comment] 2023-02-20 08:53
Duplicate of https://github.com/Nain57/Smart-AutoClicker/issues/103

**Closed** 2023-02-20 08:53 UTC
Labels: duplicate, wontfix
