### ISSUE TITLE
Size difference

### ISSUE THREAD

**Issue by alkisqwe** [Nain57/Smart-AutoClicker#399] opened 2024-03-19 19:16 UTC
smart autoclicker is the best compare to other autoclickers out there but when an image change sizes in a game the smart autoclicker fails to detect the image
![Untitled78_20240319210916](https://github.com/Nain57/Smart-AutoClicker/assets/73914940/181b34a7-4cd2-430e-beec-9f932255768c)
![Untitled78_20240319210931](https://github.com/Nain57/Smart-AutoClicker/assets/73914940/83d5fab6-9955-4ff0-84cc-2e9cb02bdfe6)

**Comment by Cyber5imon** [comment] 2024-06-25 19:04
You will need to create a different condition for each object size.

Checking for all possible object sizes for all objects would use a ton of CPU and take a long time to check many objects.

**Comment by kimxdhaha** [comment] 2024-07-09 01:04
> You will need to create a different condition for each object size.
> 
> Checking for all possible object sizes for all objects would use a ton of CPU and take a long time to check many objects.

Maybe can add a condition that user set one or more pixel color, we can set it to outer of the small object, if the that pixel turn green then we knew the object is bigger?

**Comment by Nain57** [comment] 2024-09-01 09:21
Klick'r doesn't support this kind of detection. As stated previously, you need one condition per size.

Closed as this is not a bug but normal app behaviour.

**Closed by Nain57** 2024-09-01 09:21 UTC
Labels: bug
