### ISSUE TITLE
I can not click gui

### ISSUE THREAD

**Issue by win64** [Nain57/Smart-AutoClicker#3] opened 2021-05-19 12:26 UTC
Information in title.

**Comment by NguyenDuck** [comment] 2021-05-21 02:27
You can see me for some screenshots?

**Comment by win64** [comment] 2021-05-21 04:32
yes i see screenshots

**Comment by Nain57** [comment] 2021-05-21 08:03
I might need more information to fix this.
You can't click GUI but which one ? The scenario list ? The floating menu ? Something in the dialogs ?

**Comment by win64** [comment] 2021-05-21 15:06
> I might need more information to fix this.
> You can't click GUI but which one ? The scenario list ? The floating menu ? Something in the dialogs ?

I can't click to floating menu, i click and it not get reaction. if i click to it, starting app locating under it.
P. S. sorry for my english
device:honor 6A, android version:7

**Comment by islam2hamy** [comment] 2021-06-11 07:48
Me too
Os :miui 11.0.2
Android : 7.1.2

**Comment by win64** [comment] 2021-06-14 06:12
after all ladt updates bug is not be fixed, l hoping for fix...

**Comment by Nain57** [comment] 2021-06-24 10:00
I can't reproduce it on any of my phones or the emulator.
By seeing your phones, this seems either related to MIUI or Android 7. I will try to investigate but this might be tricky without any way to validate it.

**Comment by k-y-a** [comment] 2021-07-07 12:10
> 
> 
> I can't reproduce it on any of my phones or the emulator.
> By seeing your phones, this seems either related to MIUI or Android 7. I will try to investigate but this might be tricky without any way to validate it.

Reproducible to Nox Player 7.0.1.2 using Android version 7

I think same issue as #19 #20

**Comment by Nain57** [comment] 2021-07-15 09:13
Fixed in version RC4: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.0-RC4

**Closed by Nain57** 2021-07-15 09:13 UTC
Labels: bug
