### ISSUE TITLE
The app persistently requesting to enable accessibility service that is already enabled

### ISSUE THREAD

**Issue by jonattangeraldoalbertus** [Nain57/Smart-AutoClicker#260] opened 2023-05-01 14:23 UTC
**Describe the bug**
The application persistently requesting to enable accessibility service even though it is already enabled. Moreover, neither re-enabling the accessibility service nor restarting the application solve the issue, but restarting the phone does.

**To Reproduce**
1. Do some editing on the scenario
2. The application suddenly closed on save
3. Then the bug occurs

**Expected behavior**
The application works as intended.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 8
 - Android OS version: Android 10
 - Smart AutoClicker version 2.0.2

**Comment by Nain57** [comment] 2023-05-14 09:47
Hi.
This happens when:
* The application is crashing (have never been reproduced with certitude)
* Your device have drastic background restrictions

Also, for the status of the accessibility in the Android settings: some Android OS seems to have trouble to detect the real state of this setting (especially when the OS is responsible for killing the app without reason...). When the AccessibilityService permission is granted, the Android OS is starting a service in Smart AutoClicker automatically. The state displayed in the application is always correct because it is based on this state. This bug occurs especially with heavily modified Android versions like Xiaomi/Huawei.

This bug is a duplicate of https://github.com/Nain57/Smart-AutoClicker/issues/161
I recommend to apply all following suggested actions defined for your phone brand: https://dontkillmyapp.com

**Closed by Nain57** 2023-05-14 09:47 UTC
Labels: bug

**Comment by conducked** [comment] 2023-05-14 15:05
ill have a try, I have a samsung s22 ultra so its not a cheap phone i am using island as I said which is a workstation in the phone

**Comment by Nain57** [comment] 2023-05-14 18:30
Samsung is at the top of the Don't kill my app list, so I wouldn't trust their background management too much 😅

**Comment by jonattangeraldoalbertus** [comment] 2023-05-16 01:42
I gave it a try and it doesn't seem to work. In relation to this, it seems that the cause of my issue is a consistent crash, as far as I can observe, of the application when saving the scenario after inserting a copy of existing event. Once the application crashed, the accessibility state seems desynchronized and so regardless of the changes I made in the setting, the application don't recognized it, i.e. the problem I mentioned in this issue. So far the only solution I can tell is to reboot and make sure the accessibility is off before running the application and re-enable it.
