### ISSUE TITLE
[PERFORMANCE ISSUE] After longer execution, actions will be executed twice 

### ISSUE THREAD

**Issue by talka1** [Nain57/Smart-AutoClicker#153] opened 2022-07-16 19:43 UTC
There are performance issues. after some time when you run your macro in a loop, the actions start to get executed twice after another.

Ex: See "Logo A" then do "Action A" one time. but after some time this will be executed two times after another.

**Comment by Nain57** [comment] 2022-09-08 14:28
Duplicate of: https://github.com/Nain57/Smart-AutoClicker/issues/168

**Closed by Nain57** 2022-09-08 14:28 UTC
Labels: duplicate
