### ISSUE TITLE
Landscape mode is not working on Android 14

### ISSUE THREAD

**Issue by kevisann** [Nain57/Smart-AutoClicker#338] opened 2023-11-07 22:29 UTC
Hi,

**Describe the bug**
 Creating condition with screenshot impossible when screen is in landscape mode.  The hover screenshot bar is not visible.  The smartphone is blocked since it is waiting for the screenshot to be created before it can be taken.  Force restarting the smartphone.

 **Reproduce**
 1. Click on “+” to create a new scenario
 2. Start scenario with ">"
 3. Click “Get Started”
 4. The scenario settings bar is displayed on hover.
 5. Switch to the application with the screen in landscape mode (all applications in landscape mode)
 6. Click the gear to go to the scenario settings.
 7. Click on "+" to create an event.
 8. Click “Condition.”
 9. Click on "+" to create a condition.
 10. Error here: Normally the screenshot creation bar appears on hover but in landscape mode nothing is visible and the smartphone is stuck waiting for the screenshot.

 **Expected behaviour**
 Have the menu bar display to take the screenshot to create the condition.

 **Detection scenario**
 Creation of a new simple scenario.

 **Smartphone**
 - Device: Samsung Galaxy S23
 - Android OS version: Android 14
 - Smart AutoClicker version: 2.3.4
 
Thanks for reading and future consideration of this bug.
Good day.

**Comment by kevisann** [comment] 2023-11-08 05:57
With the new version 2.3.5, the screenshot bar is displayed, however it is blocked when you need to take the screenshot, just after clicking on "[   ]".  Good day. 
Thanks again for the work !

**Comment by Nain57** [comment] 2023-11-11 13:51
Hi and thank you for your feedback.

I can't reproduce the issue on any of my devices or emulator. I suspect a landscape mode detection to not work as expected (not a surprise from Samsung, I already have 3 workaround just for them :/). Can you send me a screenshot of the Scenario dialog or Event dialog ?

**Comment by c-sanchez** [comment] 2023-11-11 14:29
I tried to reproduce the error here but it doesn't happen, everything works as expected, vertically and horizontally.
My device is a Redmi Note 11, Miui 14 with Android 13.
Surely it is what @Nain57 says and it is a problem with Samsung.

Funny thing, I was recording the screen while doing the test, when playing the video the only thing you see is when start Smart AutoClicker 😂
I guess it is normal since it is a floating window.

**Comment by kevisann** [comment] 2023-11-11 16:52
Thank you for your answers.  Instead, I'll provide you with a video to clearly see the problem.  After clicking on "[ ]" the screen is blocked, it is not frozen.  If I turn off the screen with the physical button and turn it back on, it is available for a few seconds before being blocked again.  Fortunately this allows me to access the restart to regain control.

https://github.com/Nain57/Smart-AutoClicker/assets/1338191/8fe5ceb1-66a5-42bd-9ae3-2277b50a77ee

**Comment by kevisann** [comment] 2023-11-29 21:43
Hi.
Did my video above help you identify the problem ?
Thanks again for your time.
Good day :)

**Comment by Tetrokun** [comment] 2023-12-06 18:15
Hi, I also have this issue regardless of the app I'm in when I try and trigger this in landscape mode and following the same steps as  kevisann

I have a pixel 7 pro on Android 14 with the latest version of auto clicker.

**Comment by helloyanis** [comment] 2023-12-18 09:59
Hi, I have this issue as well and I think it might be dependant on another problem, basically if the play button is greyed out when you click on the settings, then the screenshot feature will not work. See #361

**Comment by kevisann** [comment] 2024-01-22 20:42
Hi.
Did my video above help you identify the problem ?
Thanks again for your time.
Good day :)

**Comment by Nain57** [comment] 2024-01-22 22:00
Sorry I was very busy and completely forgot about this issue. 
I received the Android 14 on my phone and I'm now facing the same issue (while it works well on the emulator). This will help me to identify the issue and fix it. 
I will be busy this week, but I will have some time this weekend

**Comment by kevisann** [comment] 2024-01-22 22:29
Yes! No worries and especially no pressure ^^.
Just wanted to know if you had figured out the issue! It's just a matter of time then.
Thanks for the quick response and your time! I know what it's like ;)
Good dev ;)

**Comment by Nain57** [comment] 2024-01-27 10:30
A little update about this issue:

The following exception is raised by the system when rotating the device on Android 14 once i am recording the screen:
```
java.lang.SecurityException: Don't re-use the resultData to retrieve the same projection instance, and don't use a token that has timed out. Don't take multiple captures by invoking MediaProjection#createVirtualDisplay multiple times on the same instance.
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3087)
    at android.os.Parcel.createException(Parcel.java:3071)
    at android.os.Parcel.readException(Parcel.java:3054)
    at android.os.Parcel.readException(Parcel.java:2996)
    at android.hardware.display.IDisplayManager$Stub$Proxy.createVirtualDisplay(IDisplayManager.java:1450)
    at android.hardware.display.DisplayManagerGlobal.createVirtualDisplay(DisplayManagerGlobal.java:657)
    at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:1169)
    at android.media.projection.MediaProjection.createVirtualDisplay(MediaProjection.java:247)
    at android.media.projection.MediaProjection.createVirtualDisplay(MediaProjection.java:216)
    at com.buzbuz.smartautoclicker.core.display.DisplayRecorder.startScreenRecord(DisplayRecorder.kt:156)
    at com.buzbuz.smartautoclicker.core.processing.data.DetectorEngine$onOrientationChanged$1.invokeSuspend(DetectorEngine.kt:216)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

It seems like a protection has been added to avoid asking the screencast permission only once and saving it to use it whenever the apps want. This is really a good addition to Android from a user security perspective, but it seems like they accidentaly locked apps like Smart AutoClicker to using the permission correclty and just change the projection size when they need it (This how my app works, it basically screencast the screen in a buffer)

I'm currently trying to work around this new limitation without requesting the screencast permission for each rotation, but this might be tricky to fix. I will keep you updated !

**Comment by Nain57** [comment] 2024-01-27 13:09
I think i have found a solution, it seems to work on my OnePlus 10 Pro on Android 14, but I need further testing to ensure it is stable. 

I have linked a test apk with the fix (this is a debug app, installed allongside you "real" app with a blue icon so will keep your data intact), if anybody is willing to test:
[smartautoclicker-fDroid-debug.zip](https://github.com/Nain57/Smart-AutoClicker/files/14072344/smartautoclicker-fDroid-debug.zip)

**Comment by helloyanis** [comment] 2024-01-27 13:32
The fix seems to work on my Samsung Galaxy A52S 5G!
Thanks!!

**Comment by Nain57** [comment] 2024-01-27 13:43
It seems ok on all my test devices as well.
I will trigger a release today.

**Comment by DatPenguin** [comment] 2024-01-27 14:41
Seems to work perfectly on my Pixel 6 Android 14 too! 😊

**Comment by Nain57** [comment] 2024-01-27 15:50
Fixed in https://github.com/Nain57/Smart-AutoClicker/releases/tag/2.4.2

**Closed** 2024-01-27 15:49 UTC
Labels: bug

**Comment by kevisann** [comment] 2024-01-27 22:39
The fix works on my Samsung Galaxy S23 👍
Good job 💪, thank you ! 😉
